fb7390 fixes/tests
git-svn-id: https://svn.fhem.de/fhem/trunk@1182 2b470e98-0d58-463d-a4d8-8e2adae1ed80

diff --git a/fhem/contrib/FB7390/install b/fhem/contrib/FB7390/install
--- a/fhem/contrib/FB7390/install
+++ b/fhem/contrib/FB7390/install
@@ -57,9 +57,7 @@ if test $r != 0; then
 fi
 rm -f /var/nvi.tmp
 
-echo "########################### Starting fhem ############################"
-sync
-$home/startfhem
-
+# We have to restart with exit code 1, else the frontend tells us:
+# update failed: no error
 echo "########################### FHEM INSTALL END #########################"
-exit 1 # INSTALL_SUCCESS_REBOOT
+exit 1
